name: GitHub Actions Demo
on:
  push: 
    branches:
    - main
    paths-ignore: 
      - '.github/**'

  pull_request:
    branches:
      - main

  schedule:
    - cron: '15 6 * * 0' 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: event trigger name
      - run: echo 'Triggered by event: {{github.event_name}}';

      - name: working on branch
      - run: echo 'Current branch: {{github.branch_name}}';

      - name: files
       - run: ls -R
